version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
      cluster.name: "cluster01"
      node.name: "node01"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./eslog:/usr/share/elasticsearch/logs
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
      
volumes:
  esdata:
    driver: local